version: '2'
services:
    koupon-app:
        image: koupon
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://koupon-postgresql:5432/koupon
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://koupon-elasticsearch:9200
        ports:
            - 8080:8080
    koupon-postgresql:
        extends:
            file: postgresql.yml
            service: koupon-postgresql
    koupon-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: koupon-elasticsearch
